### ISSUE TITLE
Custom Skybox

### ISSUE THREAD

**Issue by websnooze** [OkyHp/Dynamic-Map-Light#1]
🇷🇺 : Можете ли вы добавить функцию для добавления пользовательского скайбокса?
Пример: amethyst

🇬🇧 : Can you add a function to add a custom skybox?
Example: amethyst

**Comment by OkyHp** [comment]
В планах нет поддержки. Но вы можете это сделать сами:
Укажите, к примеру вместо [`sky_csgo_night02b`](https://github.com/OkyHp/Dynamic-Map-Light/blob/main/scripting/DynamicMapLight.sp#L75) `amethyst` и укажите путь для скачивания кастомного скайбокса, в каком-то плагине, у которого есть такая возможность, пример: [VIP_Core](https://github.com/R1KO/VIP-Core)

**Comment by kozamonq** [comment]
Например, skybox "amethyst" будет иметь путь :
materials/skybox/maplight/amethyst

Должен ли я указать весь путь или только "amethyst"?

**Comment by websnooze** [comment]
Есть ли функция отключения мода и возврата к основному скайбоксу? @OkyHp

**Comment by OkyHp** [comment]
Нет, но можно добавить
